version: '3'

services:
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    ports: 
      - 27017:27017
    volumes: 
      - ./data:/data/db
  server:
    build: 
      context: ./server
    depends_on:
      - mongo
  client:
    build: 
      context: ./client