FROM alpine
WORKDIR /app

RUN apk add --update --no-cache nodejs npm ffmpeg \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev && \
    npm install -g node-gyp

COPY package*.json ./
RUN npm install
COPY . .

CMD [ "npm", "run", "dev" ]