name: Auto deploy Docker + server

on:
  push:
    branches: [ "main" ]

jobs:
  download-deploy-image:
    name: Download and run image on ssh client
    runs-on: self-hosted
    steps:
      - name: login to docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: remove old container and images
        run: |
            docker stop discord-bot || true
            docker container rm discord-bot || true
            docker image rm pxlloewe/discord-bot || true
      - name: run new image
        run: docker run --env TOKEN=${{ secrets.APP_TOKEN }} --env CLIENT_ID=${{ secrets.APP_CLIENT_ID }} --detach --name discord-bot --restart unless-stopped pxlloewe/discord-bot:latest
