name: Auto update docker

on:
  push:
    branches: [ "main" ]

jobs:
  download-deploy-files:
    name: Download and run image on ssh client
    runs-on: self-hosted
    steps:
      - name: update local files
        run: |
          cd /home/pi/discord-js-music-bot
          git pull origin --ff-only
      - name: remove old container and images
        run: |
          cd /home/pi/discord-js-music-bot
          docker container rm premiumbot-mongo-prod || true
          docker container rm premiumbot-client-prod || true
          docker container rm premiumbot-server-prod || true
      - name: run new application
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
