name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  download-deploy-image:
    name: Download and run image on ssh client
    runs-on: self-hosted
    steps:
      - name: login to docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: remove old container and images
        run: |
            docker image rm pxlloewe/discord-bot
      - name: run new image
        run: docker run --env TOKEN=${{ secrets.TOKEN }} --env CLIENT_ID=${{ secrets.CLIENT_ID }} --detach pxlloewe/discord-bot:latest
