name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  download-deploy-image:
    name: Download and run image on ssh client
    runs-on: self-hosted
    steps:
      - name: login to docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: remove old container and images
        run: |
            docker ps -a -q  --filter ancestor=pxlloewe/premium-bot
            docker image rm pxlloewe/premium-bot
      - name: pull new image
        run: docker pull pxlloewe/discord-bot:latest
